server:
  port: 5201
spring:
  application:
    name: microservicecloud-config
  cloud:
    config:
      server:
        git:
          uri: https://github.com/huanhaishijie/microservicecloud-config.git
