server:
  port: 80

#Producter:
#  url: http://192.168.12.150:8081
eureka:
  client:
    register-with-eureka: false #不注册自己
    service-url:
      defaultZone: http://eureka7001.com:7001/eureka,http://eureka7002.com:7002/eureka,http://eureka7003.com:7003/eureka
