server:
  port: 9527

spring:
  application:
    name: microservicecloud-zuul-gateway


eureka:
  client:
    service-url:
      defaultZone: http://eureka7001.com:7001/eureka,http://eureka7002.com:7002/eureka,http://eureka7003.com:7003/eureka
  instance:
    instance-id: gateway-9527.com
    prefer-ip-address: true

info:
  app.name: gateway9527
  build.version: $project.version$
zuul:
  routes:
    mydept.serviceId: microservicecloud-provider-dept
    mydept.path: /mydept/** #代理名称
  ignored-services: microservicecloud-provider-dept #隐藏真实服务 "*" 所有
  prefix: /mycloud #设置统一公共前缀
